name: deploy-supersplat
services:
  supersplat:
    container_name: supersplat
    image: d3smond/supersplat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Change to needed ports
    ipc: host
    command: ["npm", "run", "develop"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]